// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AppMain: typeof import('./src/components/layout/AppMain.vue')['default']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Item: typeof import('./src/components/layout/Sidebar/Item.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Link: typeof import('./src/components/layout/Sidebar/Link.vue')['default']
    Main: typeof import('./src/components/layout/main.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteView: typeof import('./src/components/layout/RouteView.vue')['default']
    RouteVuew: typeof import('./src/components/layout/RouteVuew.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./src/components/layout/Sidebar/SidebarItem.vue')['default']
    'SidebarItem copy': typeof import('./src/components/layout/Sidebar/SidebarItem copy.vue')['default']
  }
}

export {}
